import { SectionHeading } from "@/components/agri/SectionHeading";
import { StressBadge, stressColor, type StressLevel } from "@/components/agri/StressBadge";
import { FieldSatelliteMap } from "../components/agri/FieldSatelliteMap";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BrainCircuit, ChevronLeft, CloudRain, Droplets, Gauge, History, Loader2, Sparkles, ThermometerSun, Timer, Wind } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

const weatherLabel = (code: number) => code === 0 ? "Clear" : code <= 3 ? "Cloudy" : code <= 67 ? "Rain" : code <= 77 ? "Snow" : "Storm";
const displayDate = (value: Date | string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
type WeatherView = {
  current: { observedAt: string; temperatureC: number; humidityPercent: number; rainfallMm: number; windSpeedKph: number; weatherCode: number };
  forecast: Array<{ date: string; conditionCode: number; temperatureMaxC: number; temperatureMinC: number; precipitationMm: number; precipitationProbability: number; windSpeedKph: number; et0Mm: number }>;
  forecastRainfallMm: number;
};

export default function FieldDetail() {
  const [, params] = useRoute("/fields/:id");
  const [, setLocation] = useLocation();
  const fieldId = Number(params?.id);
  const [readingOpen, setReadingOpen] = useState(false);
  const [irrigationOpen, setIrrigationOpen] = useState(false);
  const utils = trpc.useUtils();
  const detail = trpc.agri.fields.detail.useQuery({ fieldId }, { enabled: Number.isFinite(fieldId) && fieldId > 0 });
  const history = trpc.agri.stress.history.useQuery({ fieldId }, { enabled: Number.isFinite(fieldId) && fieldId > 0 });
  const irrigation = trpc.agri.irrigation.list.useQuery({ fieldId }, { enabled: Number.isFinite(fieldId) && fieldId > 0 });
  const weather = trpc.agri.weather.latest.useQuery({ fieldId }, { enabled: Number.isFinite(fieldId) && fieldId > 0 });
  const refreshWeather = trpc.agri.weather.refresh.useMutation({ onSuccess: () => { utils.agri.weather.latest.invalidate({ fieldId }); utils.agri.fields.detail.invalidate({ fieldId }); toast.success("Seven-day field forecast refreshed"); }, onError: error => toast.error(error.message || "AgriNova could not refresh weather for this field.") });
  const generate = trpc.agri.recommendations.generate.useMutation({ onSuccess: () => { utils.agri.fields.detail.invalidate({ fieldId }); utils.agri.recommendations.latest.invalidate({ fieldId }); toast.success("Structured AI recommendation ready"); }, onError: error => toast.error(error.message || "AgriNova could not generate a recommendation.") });
  const chartData = useMemo(() => [...(history.data ?? [])].reverse().map(item => ({ date: new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(item.recordedAt)), score: item.score, level: item.riskLevel })), [history.data]);
  if (detail.isLoading) return <div className="p-8 text-sm text-[#607068]">Loading field intelligence…</div>;
  if (!detail.data) return <div className="rounded-2xl border border-[#ead1ca] bg-[#fff8f6] p-8 text-[#8a3b2d]">This field could not be found.<Button variant="link" className="ml-2 text-[#2D6A4F]" onClick={() => setLocation("/fields")}>Return to fields</Button></div>;
  const { field, latestStress, latestReading, latestRecommendation, latestIrrigation } = detail.data;
  const level = (latestStress?.riskLevel ?? "mild") as StressLevel;

  return <div className="mx-auto max-w-[1440px] space-y-7"><Button variant="ghost" className="-ml-3 text-[#2D6A4F] hover:bg-[#eaf3eb]" onClick={() => setLocation("/fields")}><ChevronLeft className="h-4 w-4" /> All fields</Button><SectionHeading eyebrow={`${field.cropType} · ${field.areaHectares.toFixed(1)} ha · ${field.soilType} soil`} title={field.name} description={`Coordinates ${field.latitude.toFixed(4)}, ${field.longitude.toFixed(4)} · ${field.cropStage} stage · ${field.irrigationMethod} irrigation`} action={<div className="flex flex-wrap gap-2"><Button variant="outline" className="border-[#bfd3c3] text-[#1e5a3c] hover:bg-[#eff7f0]" disabled={refreshWeather.isPending} onClick={() => refreshWeather.mutate({ fieldId })}><CloudRain className="h-4 w-4" /> {refreshWeather.isPending ? "Refreshing…" : "Refresh weather"}</Button><Button className="bg-[#2D6A4F] text-white hover:bg-[#1b4332]" onClick={() => setReadingOpen(true)}><Gauge className="h-4 w-4" /> Log reading</Button></div>} />
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><div className="relative overflow-hidden rounded-2xl bg-[#012d1d] p-6 text-white"><div className="absolute -right-12 -top-12 h-48 w-48 rounded-full bg-[#2D6A4F]/40 blur-2xl" /><div className="relative"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-[#b7d5c2]">Crop water-stress index</p><p className="mt-3 text-7xl font-bold tracking-[-0.07em] tabular-nums">{latestStress?.score ?? "—"}<span className="text-2xl font-medium text-[#b7d5c2]">/100</span></p></div><StressBadge level={level} className="mt-1" /></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="Soil moisture" value={latestReading ? `${Math.round(latestReading.soilMoisture)}%` : "—"} /><Metric label="Data confidence" value={latestStress ? `${latestStress.confidence}%` : "—"} /><Metric label="Last irrigation" value={latestIrrigation ? displayDate(latestIrrigation.occurredAt) : "Not recorded"} compact /></div></div></div>
      <div className="rounded-2xl border border-[#dce6dc] bg-white p-6 shadow-[0_4px_20px_rgba(27,67,50,0.05)]"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-[#587066]">AgriNova recommendation</p><h2 className="mt-1 text-xl font-semibold text-[#012d1d]">What should I do now?</h2></div><BrainCircuit className="h-6 w-6 text-[#2D6A4F]" /></div>{latestRecommendation ? <div className="mt-5 space-y-4"><p className="text-sm leading-6 text-[#42554a]">{latestRecommendation.reasoning}</p><div className="grid gap-3 sm:grid-cols-2"><Insight label="Suggested water volume" value={latestRecommendation.suggestedWaterVolume} icon={<Droplets className="h-4 w-4" />} /><Insight label="Optimal timing window" value={latestRecommendation.optimalTimingWindow} icon={<Timer className="h-4 w-4" />} /></div><p className="text-xs text-[#718078]">Method: <span className="font-medium capitalize text-[#365044]">{latestRecommendation.irrigationMethod}</span> · Confidence {latestRecommendation.confidence}% · {latestRecommendation.source === "llm" ? "AI-assisted" : "Rule-based baseline"}</p></div> : <p className="mt-5 text-sm leading-6 text-[#607068]">Log a current reading to produce a baseline recommendation.</p>}<Button className="mt-5 w-full bg-[#d7721d] text-white hover:bg-[#b95b12]" disabled={!latestReading || !latestStress || generate.isPending} onClick={() => generate.mutate({ fieldId })}>{generate.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />} {generate.isPending ? "Generating structured advice…" : "Generate AI recommendation"}</Button></div></section>
    <FieldSatelliteMap fieldId={fieldId} latitude={field.latitude} longitude={field.longitude} boundaryGeoJson={field.boundaryGeoJson} />
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,0.75fr)]"><div className="rounded-2xl border border-[#dce6dc] bg-white p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-[#587066]">Historical context</p><h2 className="mt-1 text-xl font-semibold text-[#012d1d]">Water-stress trend</h2></div><History className="h-5 w-5 text-[#2D6A4F]" /></div><div className="mt-6 h-64">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="stressFill" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor={stressColor(level)} stopOpacity={0.22} /><stop offset="95%" stopColor={stressColor(level)} stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7eee8" /><XAxis dataKey="date" tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: "#708078" }} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: "#708078" }} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid #dce6dc", boxShadow: "0 8px 20px rgba(27,67,50,0.1)" }} /><Area type="monotone" dataKey="score" stroke={stressColor(level)} strokeWidth={2.5} fill="url(#stressFill)" /></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center rounded-xl bg-[#f6f8f5] text-sm text-[#607068]">Log readings over time to reveal the field’s stress trend.</div>}</div></div>
      <WeatherPanel weather={weather.data as WeatherView | null | undefined} onRefresh={() => refreshWeather.mutate({ fieldId })} loading={refreshWeather.isPending} />
    </section>
    <section className="rounded-2xl border border-[#dce6dc] bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-[#587066]">Irrigation record</p><h2 className="mt-1 text-xl font-semibold text-[#012d1d]">Completed irrigation events</h2></div><Button className="bg-[#2D6A4F] text-white hover:bg-[#1b4332]" onClick={() => setIrrigationOpen(true)}><Droplets className="h-4 w-4" /> Log irrigation</Button></div><div className="mt-5 divide-y divide-[#edf1ed]">{irrigation.data?.length ? irrigation.data.map(event => <div key={event.id} className="grid gap-3 py-4 text-sm sm:grid-cols-[1.3fr_repeat(3,1fr)]"><p className="font-medium text-[#1c3a2a]">{displayDate(event.occurredAt)}</p><p className="text-[#607068]">{event.durationMinutes} min</p><p className="text-[#607068]">{event.waterVolumeLiters.toLocaleString()} L</p><p className="capitalize text-[#607068]">{event.method}</p></div>) : <p className="rounded-xl bg-[#f6f8f5] p-4 text-sm text-[#607068]">No irrigation event is recorded for this field yet.</p>}</div></section>
    <ReadingDialog open={readingOpen} onOpenChange={setReadingOpen} fieldId={fieldId} onSaved={() => { utils.agri.fields.detail.invalidate({ fieldId }); utils.agri.stress.history.invalidate({ fieldId }); utils.agri.dashboard.invalidate(); }} /><IrrigationDialog open={irrigationOpen} onOpenChange={setIrrigationOpen} fieldId={fieldId} defaultMethod={field.irrigationMethod} onSaved={() => { utils.agri.irrigation.list.invalidate({ fieldId }); utils.agri.fields.detail.invalidate({ fieldId }); utils.agri.dashboard.invalidate(); }} />
  </div>;
}

function Metric({ label, value, compact }: { label: string; value: string; compact?: boolean }) { return <div className="rounded-xl bg-white/10 p-3"><p className="font-mono text-[9px] font-semibold uppercase tracking-[0.12em] text-[#b7d5c2]">{label}</p><p className={`mt-1 font-semibold text-white ${compact ? "text-xs leading-5" : "text-lg"}`}>{value}</p></div>; }
function Insight({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-xl bg-[#f4f8f4] p-3"><div className="flex items-center gap-2 text-[#2D6A4F]">{icon}<p className="font-mono text-[9px] font-semibold uppercase tracking-[0.12em]">{label}</p></div><p className="mt-2 text-sm font-semibold leading-5 text-[#244333]">{value}</p></div>; }
function WeatherPanel({ weather, onRefresh, loading }: { weather: WeatherView | null | undefined; onRefresh: () => void; loading: boolean }) { return <div className="overflow-hidden rounded-2xl border border-[#d6e7ef] bg-[#f4fbff] p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-[#5b8192]">Irrigation weather context</p><h2 className="mt-1 text-xl font-semibold text-[#164f6b]">Current & 7-day outlook</h2></div><CloudRain className="h-6 w-6 text-[#287197]" /></div>{weather ? <><div className="mt-5 grid grid-cols-3 gap-2"><WeatherMetric icon={<ThermometerSun />} label="Air" value={`${Math.round(weather.current.temperatureC)}°C`} /><WeatherMetric icon={<Droplets />} label="Humidity" value={`${Math.round(weather.current.humidityPercent)}%`} /><WeatherMetric icon={<Wind />} label="Wind" value={`${Math.round(weather.current.windSpeedKph)} kph`} /></div><div className="mt-5 space-y-2">{weather.forecast.slice(0, 7).map(day => <div key={day.date} className="flex items-center justify-between rounded-lg bg-white/75 px-3 py-2 text-xs"><span className="font-medium text-[#285467]">{new Intl.DateTimeFormat(undefined, { weekday: "short", day: "numeric" }).format(new Date(day.date))}</span><span className="text-[#58798a]">{weatherLabel(day.conditionCode)} · {Math.round(day.temperatureMaxC)}° / {Math.round(day.temperatureMinC)}°</span><span className="font-mono text-[#287197]">{day.precipitationMm.toFixed(1)} mm</span></div>)}</div></> : <div className="mt-5 rounded-xl bg-white/75 p-4 text-sm leading-6 text-[#537687]">Refresh the field weather to retrieve current conditions and a seven-day forecast using the saved coordinates.</div>}<Button variant="outline" className="mt-5 w-full border-[#bed7e5] bg-white/70 text-[#216382] hover:bg-white" disabled={loading} onClick={onRefresh}>{loading ? "Refreshing…" : "Refresh field weather"}</Button></div>; }
function WeatherMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl bg-white/80 p-3 text-[#24607c]"><div className="flex items-center gap-1.5 text-[#3c7d99]">{icon}<span className="font-mono text-[9px] font-semibold uppercase tracking-[0.1em]">{label}</span></div><p className="mt-1 text-sm font-bold">{value}</p></div>; }
function ReadingDialog({ open, onOpenChange, fieldId, onSaved }: { open: boolean; onOpenChange: (value: boolean) => void; fieldId: number; onSaved: () => void }) { const [values, setValues] = useState({ soilMoisture: 24, temperatureC: 27, humidityPercent: 55 }); const mutation = trpc.agri.readings.recordManual.useMutation({ onSuccess: () => { onSaved(); onOpenChange(false); toast.success("Reading saved and water-stress index updated"); }, onError: error => toast.error(error.message || "AgriNova could not save this reading.") }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle className="text-[#012d1d]">Log a field reading</DialogTitle><DialogDescription>Manual readings are supported for the MVP and immediately update the water-stress index.</DialogDescription></DialogHeader><form className="mt-4 grid gap-4" onSubmit={(event: FormEvent) => { event.preventDefault(); mutation.mutate({ fieldId, ...values }); }}><ReadingInput label="Soil moisture (%)" value={values.soilMoisture} onChange={value => setValues(previous => ({ ...previous, soilMoisture: value }))} /><ReadingInput label="Temperature (°C)" value={values.temperatureC} onChange={value => setValues(previous => ({ ...previous, temperatureC: value }))} /><ReadingInput label="Humidity (%)" value={values.humidityPercent} onChange={value => setValues(previous => ({ ...previous, humidityPercent: value }))} /><Button disabled={mutation.isPending} className="mt-2 bg-[#2D6A4F] text-white hover:bg-[#1b4332]">{mutation.isPending ? "Calculating…" : "Save & calculate stress"}</Button></form></DialogContent></Dialog>; }
function ReadingInput({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <div className="grid gap-2"><Label>{label}</Label><Input type="number" value={value} onChange={event => onChange(Number(event.target.value))} required /></div>; }
function IrrigationDialog({ open, onOpenChange, fieldId, defaultMethod, onSaved }: { open: boolean; onOpenChange: (value: boolean) => void; fieldId: number; defaultMethod: "drip" | "sprinkler" | "flood" | "other"; onSaved: () => void }) { const [values, setValues] = useState({ date: new Date().toISOString().slice(0, 10), durationMinutes: 60, waterVolumeLiters: 1000, method: defaultMethod, notes: "" }); const mutation = trpc.agri.irrigation.record.useMutation({ onSuccess: () => { onSaved(); onOpenChange(false); toast.success("Irrigation event recorded"); }, onError: error => toast.error(error.message || "AgriNova could not record this irrigation event.") }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle className="text-[#012d1d]">Log irrigation event</DialogTitle><DialogDescription>Recording irrigation gives AgriNova the context to improve future water-stress decisions.</DialogDescription></DialogHeader><form className="mt-4 grid gap-4" onSubmit={(event: FormEvent) => { event.preventDefault(); mutation.mutate({ fieldId, occurredAt: new Date(`${values.date}T06:00:00`), durationMinutes: values.durationMinutes, waterVolumeLiters: values.waterVolumeLiters, method: values.method, notes: values.notes || undefined }); }}><div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label>Date</Label><Input type="date" value={values.date} onChange={event => setValues(previous => ({ ...previous, date: event.target.value }))} /></div><ReadingInput label="Duration (minutes)" value={values.durationMinutes} onChange={value => setValues(previous => ({ ...previous, durationMinutes: value }))} /></div><div className="grid gap-4 sm:grid-cols-2"><ReadingInput label="Water volume (litres)" value={values.waterVolumeLiters} onChange={value => setValues(previous => ({ ...previous, waterVolumeLiters: value }))} /><div className="grid gap-2"><Label>Irrigation method</Label><Select value={values.method} onValueChange={value => setValues(previous => ({ ...previous, method: value as typeof defaultMethod }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["drip", "sprinkler", "flood", "other"].map(method => <SelectItem className="capitalize" key={method} value={method}>{method}</SelectItem>)}</SelectContent></Select></div></div><div className="grid gap-2"><Label>Notes (optional)</Label><Textarea value={values.notes} onChange={event => setValues(previous => ({ ...previous, notes: event.target.value }))} /></div><Button disabled={mutation.isPending} className="bg-[#2D6A4F] text-white hover:bg-[#1b4332]">{mutation.isPending ? "Saving…" : "Record irrigation"}</Button></form></DialogContent></Dialog>; }
